### ISSUE TITLE
Authenvvars with dockerized Dokuwiki

### ISSUE THREAD

**Issue by korshavn** [chrille69/dokuwiki-plugin-authenvvars#1]
Hi.

I'd love to make use of your plugin for my dokuwiki setup. It would be just what I need!

My setup is the docker image from https://github.com/linuxserver/docker-dokuwiki so my first question is if this perhaps is a newer version of Dokuwiki that authenvvars does not support?
Furthermore, since the docker image comes with an nginx embedded, I have a local Apache in front of the docker container and the Apache is where I use auth_mod_openidc. So the OIDC_CLAIM headers are passed as http headers to the nginx inside the container. I assume the http headers from auth_mod_openidc is correctly converted to enviroment variables thru the fastcgi setting fastcgi_pass_request_headers on (should be default on according to doc) 

However, after having installed authenvvars according to the installation instructions, I also had to enable authennvars (setting $conf['authtype'] = 'authenvvars' in conf/dokuwiki.php) which you did not write in your doc... is it maybe due to different versions of Dokuwiki?

But I get the following error message in the nginx error log: 

2021/05/23 12:50:50 [error] 366#366: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function act_redirect() in /config/dokuwiki/lib/plugins/authenvvars/action.php:35
Stack trace:
#0 /app/dokuwiki/inc/Extension/EventHandler.php(81): action_plugin_authenvvars->skip_login_action()
#1 /app/dokuwiki/inc/Extension/Event.php(93): dokuwiki\Extension\EventHandler->process_event()
#2 /app/dokuwiki/inc/ActionRouter.php(88): dokuwiki\Extension\Event->advise_after()
#3 /app/dokuwiki/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction()
#4 /app/dokuwiki/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
#5 /app/dokuwiki/inc/actions.php(16): dokuwiki\ActionRouter::getInstance()
#6 /app/dokuwiki/doku.php(122): act_dispatch()
#7 {main}
  thrown in /config/dokuwiki/lib/plugins/authenvvars/action.php on line 35" while reading response header from upstream, client: 172.21.0.1, server: _, request: "POST /doku.php?id=start HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx", referrer: "https://xxxx/wiki/doku.php?id=start&do=admin&page=extension&tab=plugins"

Your help or advise would be very much appreciated! Thank you!
:-)

**Comment by chrille69** [comment]
Hello Leif!

I developed this plugin for 'Frusterick Manners'. This is the reason why the documentation does not match to 'Greebo' or 'Hogfather'. We do not change the dokuwiki version for our site every time.

However, perhaps this fix could help:

Find the action.php file of this plugin. It should be located under

`/my/dokuwiki/path/lib/plugins/authenvvars/action.php`

and replace the act_redirect call to send_redirect as follows:

```
        //act_redirect($ID, 'show');
        send_redirect($ID, '', 'show');
```

Does ist work now?

Greetings
Christian Hoffmann

**Comment by korshavn** [comment]
Excellent! It worked. :-) Thank you!
Best regards, Leif
